export const COSMOS_DB_CONTAINERS = {
  PRODUCTS: 'products',
  REPAIR_ORDERS: 'repairOrders',
  SALES: 'sales',
};

export const REPAIR_STATUSES = {
  PENDING_DIAGNOSIS: 'PENDING_DIAGNOSIS',
  DIAGNOSIS_COMPLETE: 'DIAGNOSIS_COMPLETE',
  REPAIR_ACCEPTED: 'REPAIR_ACCEPTED',
  REPAIR_REJECTED: 'REPAIR_REJECTED',
  IN_REPAIR: 'IN_REPAIR',
  REPAIRED_PENDING_PICKUP: 'REPAIRED_PENDING_PICKUP',
  DELIVERED: 'DELIVERED',
};

export const PAYMENT_METHODS = {
  CASH: 'CASH',
  CARD: 'CARD',
};
