import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/components/providers/AuthProvider";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';

export const metadata: Metadata = {
  title: "Workshop App",
  description: "Generated by create next app",
};

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <AppRouterCacheProvider>
          <AuthProvider>
            {children}
            <ToastContainer position="top-right" autoClose={5000} hideProgressBar={false} />
          </AuthProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}