"use client";

import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Container, Dialog, DialogActions, DialogContent, DialogTitle, Divider, FormControl, Grid, InputLabel, MenuItem, Paper, Select, Stack, Tab, Tabs, TextField, Typography } from '@mui/material';
import { Icon } from '@iconify/react';

type Financial = { period: { from: string; to: string; groupBy: 'day' | 'month' }; kpis: Record<string, number>; trend: { label: string; revenue: number; expenses: number; profit: number; cashFlow: number }[]; paymentMethods: Record<string, number>; expenseByCategory: Record<string, number>; topProducts: { name: string; quantity: number; revenue: number; cost: number; margin: number }[]; inventory: { costValue: number; saleValue: number; units: number; lowStock: number }; projection: { revenue30: number; operatingProfit30: number; basisDays: number }; expensesReady: boolean };
type Expense = { id: string; category: string; description: string; amount: number; expense_date: string; payment_method: string; supplier_name?: string | null };
const money = (n: number) => new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN' }).format(Number(n || 0));
const formatNumber = (n: number) => new Intl.NumberFormat('es-MX').format(Number(n || 0));
const today = () => new Date().toISOString().slice(0, 10);
const monthStart = () => { const d = new Date(); return new Date(d.getFullYear(), d.getMonth(), 1).toISOString().slice(0, 10); };
const category: Record<string, string> = { rent: 'Renta', payroll: 'Nómina', utilities: 'Servicios', inventory_purchase: 'Compra de inventario', transport: 'Transporte', tools: 'Herramientas', marketing: 'Marketing', maintenance: 'Mantenimiento', other: 'Otros' };
const payment: Record<string, string> = { cash: 'Efectivo', card: 'Tarjeta', transfer: 'Transferencia', other: 'Otro' };

function Kpi({ title, value, icon, color = 'primary', note }: { title: string; value: string; icon: string; color?: 'primary' | 'success' | 'warning' | 'error'; note: string }) {
  return <Card variant="outlined" sx={{ height: '100%', borderRadius: 3 }}><CardContent sx={{ p: 2.25, '&:last-child': { pb: 2.25 } }}><Stack direction="row" justifyContent="space-between" gap={1}><Box><Typography variant="body2" color="text.secondary">{title}</Typography><Typography variant="h5" sx={{ mt: .75, fontWeight: 800 }}>{value}</Typography><Typography variant="caption" color="text.secondary">{note}</Typography></Box><Box sx={{ color: `${color}.main`, bgcolor: `${color}.lighter`, borderRadius: 2, p: 1, height: 40 }}><Icon icon={icon} width={22} /></Box></Stack></CardContent></Card>;
}
function Bars({ points, field = 'revenue', color = '#00a76f' }: { points: Financial['trend']; field?: 'revenue' | 'expenses' | 'profit' | 'cashFlow'; color?: string }) {
  const max = Math.max(...points.map(p => Math.abs(p[field])), 1);
  if (!points.length) return <Typography align="center" color="text.secondary" sx={{ py: 8 }}>Aún no hay movimientos en este periodo.</Typography>;
  return <Box sx={{ height: 220, display: 'flex', alignItems: 'end', gap: .75, pt: 2, overflow: 'hidden' }}>{points.slice(-18).map((point, index) => <Box title={`${point.label}: ${money(point[field])}`} key={`${point.label}${index}`} sx={{ minWidth: 8, flex: 1, height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'end', flexDirection: 'column' }}><Box sx={{ width: '100%', maxWidth: 26, minHeight: 8, height: `${Math.round(Math.abs(point[field]) / max * 155)}px`, borderRadius: '6px 6px 2px 2px', bgcolor: point[field] < 0 ? 'error.main' : color }} /><Typography variant="caption" sx={{ mt: 1, fontSize: 10, transform: 'rotate(-35deg)', whiteSpace: 'nowrap', color: 'text.secondary' }}>{point.label}</Typography></Box>)}</Box>;
}

export default function ReportsPage() {
  const [data, setData] = useState<Financial | null>(null), [expenses, setExpenses] = useState<Expense[]>([]), [branches, setBranches] = useState<{ id: string; name: string }[]>([]);
  const [from, setFrom] = useState(monthStart), [to, setTo] = useState(today), [branchId, setBranchId] = useState(''), [groupBy, setGroupBy] = useState<'day' | 'month'>('day'), [tab, setTab] = useState(0), [loading, setLoading] = useState(true), [error, setError] = useState(''), [open, setOpen] = useState(false), [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ category: 'utilities', description: '', amount: '', expenseDate: today(), paymentMethod: 'cash', supplierName: '', reference: '' });
  const query = useMemo(() => new URLSearchParams({ from, to, groupBy, ...(branchId ? { branchId } : {}) }).toString(), [from, to, groupBy, branchId]);
  const load = useCallback(async () => { setLoading(true); try { const [financeResponse, expenseResponse] = await Promise.all([fetch(`/api/reports/financial?${query}`), fetch(`/api/reports/expenses?${query}`)]); const finance = await financeResponse.json(), expense = await expenseResponse.json(); if (!financeResponse.ok || !finance.success) throw new Error(finance.error || 'No se pudo cargar el reporte'); setData(finance.data); setExpenses(expense.success ? expense.data : []); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo cargar el reporte'); } finally { setLoading(false); } }, [query]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { fetch('/api/branches').then(r => r.json()).then(r => r.success && setBranches(r.data || [])).catch(() => undefined); }, []);
  const quick = (range: string) => { const e = new Date(), b = new Date(); if (range === 'week') b.setDate(e.getDate() - 6); if (range === 'month') b.setDate(1); if (range === 'quarter') b.setMonth(e.getMonth() - 2, 1); if (range === 'year') b.setMonth(0, 1); setFrom(b.toISOString().slice(0, 10)); setTo(e.toISOString().slice(0, 10)); };
  const createExpense = async () => { setSaving(true); try { const response = await fetch('/api/reports/expenses', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, amount: Number(form.amount), branchId: branchId || undefined }) }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.error || 'No se pudo registrar el gasto'); setOpen(false); setForm({ category: 'utilities', description: '', amount: '', expenseDate: today(), paymentMethod: 'cash', supplierName: '', reference: '' }); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo registrar el gasto'); } finally { setSaving(false); } };
  const k = data?.kpis || {};
  return <Container maxWidth="xl" sx={{ py: { xs: 2, md: 4 } }}>
    <Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" gap={2} sx={{ mb: 3 }}><Box><Typography variant="h3" component="h1" sx={{ fontSize: { xs: 28, md: 34 }, fontWeight: 800 }}>Reportes financieros</Typography><Typography color="text.secondary">Ventas, rentabilidad, flujo e inventario en una sola vista.</Typography></Box><Button variant="contained" onClick={() => setOpen(true)} startIcon={<Icon icon="eva:plus-fill" />}>Registrar gasto</Button></Stack>
    {error && <Alert severity="error" sx={{ mb: 2 }} onClose={() => setError('')}>{error}</Alert>}
    <Paper variant="outlined" sx={{ p: { xs: 1.5, sm: 2 }, mb: 3, borderRadius: 3 }}><Stack spacing={1.25}><Stack direction={{ xs: 'column', lg: 'row' }} gap={1.25}><TextField size="small" label="Desde" type="date" value={from} onChange={e => setFrom(e.target.value)} InputLabelProps={{ shrink: true }} /><TextField size="small" label="Hasta" type="date" value={to} onChange={e => setTo(e.target.value)} InputLabelProps={{ shrink: true }} /><FormControl size="small" sx={{ minWidth: 190 }}><InputLabel>Sucursal</InputLabel><Select label="Sucursal" value={branchId} onChange={e => setBranchId(e.target.value)}><MenuItem value="">Todas las sucursales</MenuItem>{branches.map(b => <MenuItem key={b.id} value={b.id}>{b.name}</MenuItem>)}</Select></FormControl><FormControl size="small" sx={{ minWidth: 160 }}><InputLabel>Agrupar</InputLabel><Select label="Agrupar" value={groupBy} onChange={e => setGroupBy(e.target.value as 'day' | 'month')}><MenuItem value="day">Por día</MenuItem><MenuItem value="month">Por mes</MenuItem></Select></FormControl><Button variant="outlined" onClick={load} startIcon={<Icon icon="eva:refresh-fill" />}>Actualizar</Button></Stack><Stack direction="row" gap={1} flexWrap="wrap">{[['today', 'Hoy'], ['week', '7 días'], ['month', 'Este mes'], ['quarter', 'Trimestre'], ['year', 'Año']].map(([range, label]) => <Chip key={range} label={label} clickable variant="outlined" onClick={() => quick(range)} />)}</Stack></Stack></Paper>
    <Tabs value={tab} onChange={(_, value) => setTab(value)} variant="scrollable" scrollButtons="auto" sx={{ mb: 2, '& .MuiTab-root': { fontWeight: 700 } }}><Tab label="Resumen ejecutivo" /><Tab label="Flujo" /><Tab label="Rentabilidad" /><Tab label="Inventario" /><Tab label="Gastos" /></Tabs>
    {loading ? <Box sx={{ minHeight: 400, display: 'grid', placeItems: 'center' }}><CircularProgress /></Box> : data && <>
      {tab === 0 && <Stack spacing={2.5}><Grid container spacing={2}><Grid size={{ xs: 12, sm: 6, lg: 3 }}><Kpi title="Ingresos cobrados" value={money(k.grossRevenue)} icon="eva:trending-up-fill" color="success" note={`${formatNumber(k.salesCount)} ventas · ticket ${money(k.averageTicket)}`} /></Grid><Grid size={{ xs: 12, sm: 6, lg: 3 }}><Kpi title="Utilidad bruta" value={money(k.grossProfit)} icon="eva:pie-chart-2-fill" note={`Margen ${Number(k.grossMargin).toFixed(1)}%`} /></Grid><Grid size={{ xs: 12, sm: 6, lg: 3 }}><Kpi title="Resultado operativo" value={money(k.operatingProfit)} icon="eva:activity-fill" color={k.operatingProfit >= 0 ? 'success' : 'error'} note="Después de gastos operativos" /></Grid><Grid size={{ xs: 12, sm: 6, lg: 3 }}><Kpi title="Flujo neto" value={money(k.cashFlow)} icon="eva:swap-fill" color={k.cashFlow >= 0 ? 'success' : 'warning'} note="Cobros menos todos los gastos" /></Grid></Grid><Grid container spacing={2}><Grid size={{ xs: 12, lg: 8 }}><Card variant="outlined" sx={{ borderRadius: 3, height: '100%' }}><CardContent><Typography variant="h6" fontWeight={800}>Tendencia de ingresos</Typography><Typography variant="body2" color="text.secondary">Cobros del periodo seleccionado</Typography><Bars points={data.trend} /></CardContent></Card></Grid><Grid size={{ xs: 12, lg: 4 }}><Card variant="outlined" sx={{ borderRadius: 3, height: '100%' }}><CardContent><Typography variant="h6" fontWeight={800}>Pulso del negocio</Typography><Stack spacing={1.5} divider={<Divider flexItem />} sx={{ mt: 2 }}><Box><Typography variant="body2" color="text.secondary">Impuestos trasladados</Typography><Typography variant="h6" fontWeight={800}>{money(k.taxes)}</Typography></Box><Box><Typography variant="body2" color="text.secondary">Ventas de reparaciones</Typography><Typography variant="h6" fontWeight={800}>{formatNumber(k.repairSales)}</Typography></Box><Box><Typography variant="body2" color="text.secondary">Proyección operativa a 30 días</Typography><Typography variant="h6" color="success.main" fontWeight={800}>{money(data.projection.operatingProfit30)}</Typography><Typography variant="caption" color="text.secondary">Basada en {data.projection.basisDays} días.</Typography></Box></Stack></CardContent></Card></Grid></Grid><Alert severity={k.cashFlow >= 0 ? 'success' : 'warning'}>{k.cashFlow >= 0 ? 'El flujo del periodo es positivo. La proyección te ayuda a anticipar compras y gastos.' : 'Los gastos superan los cobros del periodo. Revisa el flujo antes de hacer compras nuevas.'}</Alert></Stack>}
      {tab === 1 && <Grid container spacing={2}><Grid size={{ xs: 12, lg: 8 }}><Card variant="outlined" sx={{ borderRadius: 3 }}><CardContent><Typography variant="h6" fontWeight={800}>Flujo neto</Typography><Typography variant="body2" color="text.secondary">Cobros menos gastos registrados.</Typography><Bars points={data.trend} field="cashFlow" color="#0ea5c9" /></CardContent></Card></Grid><Grid size={{ xs: 12, lg: 4 }}><Card variant="outlined" sx={{ borderRadius: 3 }}><CardContent><Typography variant="h6" fontWeight={800}>Medios de cobro</Typography><Stack spacing={1.5} sx={{ mt: 2 }}>{Object.entries(data.paymentMethods).length ? Object.entries(data.paymentMethods).map(([method, value]) => <Stack key={method} direction="row" justifyContent="space-between"><Typography color="text.secondary">{payment[method] || method}</Typography><Typography fontWeight={800}>{money(value)}</Typography></Stack>) : <Typography color="text.secondary">Sin cobros en el periodo.</Typography>}</Stack></CardContent></Card></Grid></Grid>}
      {tab === 2 && <Stack spacing={2}><Grid container spacing={2}><Grid size={{ xs: 12, md: 4 }}><Kpi title="Ventas netas sin IVA" value={money(k.netRevenue)} icon="eva:bar-chart-fill" note="Base para medir margen" /></Grid><Grid size={{ xs: 12, md: 4 }}><Kpi title="Costo de ventas" value={money(k.cogs)} icon="eva:shopping-bag-fill" color="warning" note="Costo histórico de productos" /></Grid><Grid size={{ xs: 12, md: 4 }}><Kpi title="Gastos operativos" value={money(k.operatingExpenses)} icon="eva:credit-card-fill" color="error" note="Sin compras de inventario" /></Grid></Grid><Card variant="outlined" sx={{ borderRadius: 3 }}><CardContent><Typography variant="h6" fontWeight={800}>Productos con mayor contribución</Typography>{data.topProducts.length ? data.topProducts.map(p => <Stack key={p.name} direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" sx={{ py: 1.5, borderBottom: '1px dashed', borderColor: 'divider' }}><Box><Typography fontWeight={700}>{p.name}</Typography><Typography variant="body2" color="text.secondary">{formatNumber(p.quantity)} unidades · ventas {money(p.revenue)}</Typography></Box><Typography color="success.main" fontWeight={800}>Margen {money(p.margin)}</Typography></Stack>) : <Typography color="text.secondary" sx={{ py: 5, display: 'block', textAlign: 'center' }}>Sin productos vendidos en el periodo.</Typography>}</CardContent></Card></Stack>}
      {tab === 3 && <Stack spacing={2}><Grid container spacing={2}><Grid size={{ xs: 12, sm: 6, lg: 3 }}><Kpi title="Valor a costo" value={money(data.inventory.costValue)} icon="eva:archive-fill" note={`${formatNumber(data.inventory.units)} unidades`} /></Grid><Grid size={{ xs: 12, sm: 6, lg: 3 }}><Kpi title="Valor potencial" value={money(data.inventory.saleValue)} icon="eva:trending-up-fill" color="success" note="Valor de venta estimado" /></Grid><Grid size={{ xs: 12, sm: 6, lg: 3 }}><Kpi title="Margen potencial" value={money(data.inventory.saleValue - data.inventory.costValue)} icon="eva:plus-circle-fill" color="success" note="Con el stock actual" /></Grid><Grid size={{ xs: 12, sm: 6, lg: 3 }}><Kpi title="Alertas de mínimo" value={formatNumber(data.inventory.lowStock)} icon="eva:alert-triangle-fill" color={data.inventory.lowStock ? 'warning' : 'success'} note="Productos en o bajo mínimo" /></Grid></Grid><Alert severity="info">El inventario se valora con su costo y precio actuales. La rentabilidad de venta usa el costo guardado cuando se realizó el cobro.</Alert></Stack>}
      {tab === 4 && <Stack spacing={2}><Card variant="outlined" sx={{ borderRadius: 3 }}><CardContent><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" gap={1}><Box><Typography variant="h6" fontWeight={800}>Gastos del periodo</Typography><Typography variant="body2" color="text.secondary">Registra costos reales para completar la lectura financiera.</Typography></Box><Button variant="contained" onClick={() => setOpen(true)}>Nuevo gasto</Button></Stack><Grid container spacing={1.5} sx={{ mt: 1 }}>{Object.entries(data.expenseByCategory).map(([key, value]) => <Grid key={key} size={{ xs: 6, sm: 4, lg: 3 }}><Paper variant="outlined" sx={{ p: 1.5, borderRadius: 2 }}><Typography variant="body2" color="text.secondary">{category[key] || key}</Typography><Typography fontWeight={800}>{money(value)}</Typography></Paper></Grid>)}</Grid></CardContent></Card><Card variant="outlined" sx={{ borderRadius: 3 }}><CardContent><Typography variant="h6" fontWeight={800} sx={{ mb: 1 }}>Movimientos registrados</Typography>{!data.expensesReady ? <Alert severity="warning">Falta aplicar la migración financiera para habilitar el libro de gastos.</Alert> : expenses.length ? expenses.map(e => <Stack key={e.id} direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" gap={1} sx={{ p: 1.5, borderBottom: '1px solid', borderColor: 'divider' }}><Box><Typography fontWeight={700}>{e.description}</Typography><Typography variant="body2" color="text.secondary">{category[e.category] || e.category}{e.supplier_name ? ` · ${e.supplier_name}` : ''} · {new Date(`${e.expense_date}T12:00:00`).toLocaleDateString('es-MX')}</Typography></Box><Stack direction="row" spacing={1}><Chip size="small" label={payment[e.payment_method] || e.payment_method} variant="outlined" /><Typography fontWeight={800}>{money(e.amount)}</Typography></Stack></Stack>) : <Typography color="text.secondary" sx={{ py: 5, display: 'block', textAlign: 'center' }}>Todavía no has registrado gastos en este periodo.</Typography>}</CardContent></Card></Stack>}
    </>}
    <Dialog open={open} onClose={() => !saving && setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Registrar gasto</DialogTitle><DialogContent dividers><Stack spacing={2} sx={{ pt: .5 }}><Alert severity="info">Registra el importe final pagado para reflejar el flujo real.</Alert><FormControl fullWidth><InputLabel>Categoría</InputLabel><Select label="Categoría" value={form.category} onChange={e => setForm(f => ({ ...f, category: e.target.value }))}>{Object.entries(category).map(([value, label]) => <MenuItem key={value} value={value}>{label}</MenuItem>)}</Select></FormControl><TextField required autoFocus fullWidth label="Concepto o descripción" value={form.description} onChange={e => setForm(f => ({ ...f, description: e.target.value }))} /><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField required fullWidth type="number" label="Importe pagado" inputProps={{ min: 0, step: .01 }} value={form.amount} onChange={e => setForm(f => ({ ...f, amount: e.target.value }))} /><TextField required fullWidth type="date" label="Fecha" InputLabelProps={{ shrink: true }} value={form.expenseDate} onChange={e => setForm(f => ({ ...f, expenseDate: e.target.value }))} /></Stack><FormControl fullWidth><InputLabel>Método de pago</InputLabel><Select label="Método de pago" value={form.paymentMethod} onChange={e => setForm(f => ({ ...f, paymentMethod: e.target.value }))}>{Object.entries(payment).map(([value, label]) => <MenuItem key={value} value={value}>{label}</MenuItem>)}</Select></FormControl><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField fullWidth label="Proveedor (opcional)" value={form.supplierName} onChange={e => setForm(f => ({ ...f, supplierName: e.target.value }))} /><TextField fullWidth label="Referencia (opcional)" value={form.reference} onChange={e => setForm(f => ({ ...f, reference: e.target.value }))} /></Stack></Stack></DialogContent><DialogActions sx={{ p: 2 }}><Button onClick={() => setOpen(false)}>Cancelar</Button><Button variant="contained" disabled={saving || !form.description.trim() || !Number(form.amount)} onClick={createExpense}>{saving ? 'Guardando…' : 'Guardar gasto'}</Button></DialogActions></Dialog>
  </Container>;
}
